- name: download traefik
  become: true
  get_url:
    url: "https://github.com/containous/traefik/releases/download/v{{ traefik_version }}/traefik_linux-amd64"
    dest: /tmp/
    remote_src: True
  tags:
    - traefik

- name: setup traefik
  become: true
  copy:
    src: "/tmp/traefik_linux-amd64"
    dest: "/usr/bin/traefik"
    mode: 0755
    remote_src: True
  notify:
    - restart traefik
  tags:
    - traefik

- name: setup traefik systemd service
  become: true
  template:
    src: "traefik/traefik.service.j2"
    dest: "/etc/systemd/system/traefik.service"
    mode: 0644
  tags:
    - traefik

- name: setup traefik toml configuration
  become: true
  template:
    src: "traefik/traefik.toml.j2"
    dest: "/etc/traefik.toml"
    mode: 0644
  notify:
    - restart traefik
  tags:
    - traefik

- name: start traefik
  service:
    name: traefik
    state: started
    enabled: yes
  notify:
    - wait for traefik to run
