---
- name: Configure /etc/security/limits.conf
  become: true
  template: src=limits.conf.j2 dest=/etc/security/limits.conf
  register: ulimit_change

- name: Change ulimit for this session
  become: true
  shell: "ulimit -n {{ limit_nofile }}"
  when: ulimit_change|changed
