# This guide is optimized for Vagrant 1.7 and above.
# Although versions 1.6.x should behave very similarly, it is recommended
# to upgrade instead of disabling the requirement below.
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  config.vm.define 'ubuntu-1' do |vagrant|
   vagrant.vm.box = "bento/ubuntu-16.04"
   vagrant.vm.network "private_network", ip: "172.16.3.2"
   vagrant.vm.network "forwarded_port", guest: 22, host: 2202, id: 'ssh'
   vagrant.vm.network "forwarded_port", guest: 8080, host: 8081
  end

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = true

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
