- name: restart traefik
  become: true
  service:
    name: traefik
    state: restarted
  notify:
    - wait for traefik to run

- name: wait for traefik to run
  become: true
  wait_for:
    port: 80
    delay: 5
